name: "Sign PowerShellScript"
description: "Self-sign powershell scripts"
author: "otivedani@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "blue"
