name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello windows action
    runs-on: windows-latest
    steps:
      - name: Display the path
        run: echo ${env:PATH}
        shell: pwsh
